name: Buildpack

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: docker-login
      run: echo "${{ secrets.DockerPassword }}" | docker login -u "${{ secrets.DockerUsername }}" --password-stdin
    - name: build
      uses: crswty/buildpack-action@pr1
      env:
        IMAGE_NAME: crswty/spring-music:latest
        VARS: SERVER_PORT=8090 TEST=hi
    - name: docker-push
      run: docker push crswty/spring-music:latest

