name: Buildpack

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: docker-login
      env:
       DOCKER_USERNAME: ${{ secrets.DockerUsername }}
       DOCKER_PASSWORD: ${{ secrets.DockerPassword }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: build
      uses: crswty/buildpack-action@master
      env:
        PUBLISH: true
        IMAGE_NAME: crswty/spring-music:latest

