name: Buildpack

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: build
      uses: crswty/buildpack-action@master
    - name: login
      uses: "actions/docker/login@master"
      secrets:
      - ${{ secrets.DockerUsername }}
      - ${{ secrets.DockerPassword }}
