name: Buildpack

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: login
      uses: "actions/docker/login@master"
      env:
       DOCKER_USERNAME: ${{ secrets.DockerUsername }}
       DOCKER_PASSWORD: ${{ secrets.DockerPassword }}
    - name: build
      uses: crswty/buildpack-action@master
    
